### ISSUE TITLE
Allow Hugo categories to have qualifiers other than "Writer"

### ISSUE THREAD

**Issue by arkoebel** [maailma/kansa#56]
This is cosmetic (and only for the Hugo admin's benefit, I believe), but some it would be nice if some categories could display something other than "Writer": like "Editor" or "Artist"

**Comment by arkoebel** [comment]
I can't reproduce it on my testing box (using your latest code-base). 
The issue was framed like this by Nicholas: 'at nominations phase, in the canonicalisation interfaces for the Artist and Editor categories (as far as I remember), the data fields for the nominees are designated “Writer”'. 
As I don't know every feature yet, I might not go to the right place. 

Anyway, maybe that was an issue in the early system 2 years ago and it got fixed along the way?

**Comment by eemeli** [comment]
Yeah, I'm pretty sure that this is not a current issue. Please re-open this issue or file a new one if it still shows up in some manner?
